import type { AIProviderDefinition } from '../types/public';

export const builtInProviders: AIProviderDefinition[] = [
  {
    id: 'openai',
    label: 'OpenAI',
    credentialLabel: 'OpenAI API key',
    credentialPlaceholder: 'sk-...',
    supportsBYOK: true,
    helpText: 'Use your own OpenAI key for direct OpenAI model access.',
    docsUrl: 'https://platform.openai.com/api-keys',
    models: [
      {
        id: 'gpt-4.1-mini',
        label: 'GPT-4.1 Mini',
        provider: 'openai',
        capabilities: { text: true, structuredOutput: true, streaming: true },
        costHint: 'medium',
        status: 'active',
      },
      {
        id: 'gpt-4.1',
        label: 'GPT-4.1',
        provider: 'openai',
        capabilities: { text: true, reasoning: true, structuredOutput: true, streaming: true },
        costHint: 'high',
        status: 'active',
      },
    ],
  },
  {
    id: 'anthropic',
    label: 'Anthropic',
    credentialLabel: 'Anthropic API key',
    credentialPlaceholder: 'sk-ant-...',
    supportsBYOK: true,
    helpText: 'Use your own Anthropic key for Claude models.',
    docsUrl: 'https://console.anthropic.com/settings/keys',
    models: [
      {
        id: 'claude-3-7-sonnet',
        label: 'Claude 3.7 Sonnet',
        provider: 'anthropic',
        capabilities: { text: true, reasoning: true, vision: true, streaming: true },
        costHint: 'high',
        status: 'active',
      },
      {
        id: 'claude-3-5-haiku',
        label: 'Claude 3.5 Haiku',
        provider: 'anthropic',
        capabilities: { text: true, streaming: true },
        costHint: 'medium',
        status: 'active',
      },
    ],
  },
  {
    id: 'google',
    label: 'Google AI',
    credentialLabel: 'Google AI API key',
    credentialPlaceholder: 'AIza...',
    supportsBYOK: true,
    helpText: 'Use your own Google AI key for Gemini access.',
    docsUrl: 'https://aistudio.google.com/app/apikey',
    models: [
      {
        id: 'gemini-2.0-flash',
        label: 'Gemini 2.0 Flash',
        provider: 'google',
        capabilities: { text: true, vision: true, structuredOutput: true, streaming: true },
        costHint: 'low',
        status: 'active',
      },
    ],
  },
  {
    id: 'openrouter',
    label: 'OpenRouter',
    credentialLabel: 'OpenRouter API key',
    credentialPlaceholder: 'sk-or-...',
    supportsBYOK: true,
    helpText: 'Use your own OpenRouter key to access curated third-party models.',
    docsUrl: 'https://openrouter.ai/keys',
    models: [
      {
        id: 'openrouter/anthropic/claude-3.5-sonnet',
        label: 'Claude 3.5 Sonnet via OpenRouter',
        provider: 'openrouter',
        capabilities: { text: true, reasoning: true, streaming: true },
        costHint: 'high',
        status: 'active',
      },
      {
        id: 'openrouter/openai/gpt-4o-mini',
        label: 'GPT-4o Mini via OpenRouter',
        provider: 'openrouter',
        capabilities: { text: true, streaming: true },
        costHint: 'medium',
        status: 'active',
      },
    ],
  },
];
